name: code_scout
description: 'Versatile Flutter logger for development and QA. Supports console and socket-based logging, enabling remote monitoring of app behavior, API calls, and analytics without debug connections.'
version: 1.0.0
homepage:

environment:
  sdk: ^3.5.0
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  convert: ^3.1.2
  logger:
    path: ./logger
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/cwa_setting.png
