name: code_scout_http
description: 'HTTP client wrapper for CodeScout. Automatically captures network requests, responses, and errors.'
version: 1.0.3
homepage: https://codescout.tech
repository: https://github.com/getcodescout/code_scout_flutter/tree/main/packages/code_scout_http

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  code_scout: ^1.5.0
  http: '>=1.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
